### Sing Up User
POST http://localhost:3000/auth/singup
Content-Type: application/json

{
    "name":"test",
    "email":"test@mail.com",
    "password":"Password_1234"

}

### Sing In User
POST http://localhost:3000/auth/singin
Content-Type: application/json

{
    "email":"test@mail.com",
    "password":"Password_1234"

}

### Testing Token
GET  http://localhost:3000/auth/protected
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJpZCI6MSwiZW1haWwiOiJ0ZXN0QG1haWwuY29tIiwiaWF0IjoxNzI1NjMzNzg3LCJleHAiOjE3MjU3MjAxODd9.oP3aS_xOE-zkToUt82EMe7y-GhqQeWCHpqZTIiVr9bk